#
# Vivado (TM) v2015.1 (64-bit)
#
# build_new.tcl: Tcl script for re-creating project 'ecgSys'
#
# Generated by Vivado on Thu May 21 14:03:29 +0300 2015
# IP Build 1209967 on Tue Apr 21 11:39:20 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_new.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1.bd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/projects/ecgSystem/src/coe/real_16_PB_1_40.coe"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/projects/ecgSystem/src/coe/diff_05_45.coe"
#    "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/imports/hdl/design_1_wrapper.vhd"
#    "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Unit_0_0/design_1_ECG_Unit_0_0.upgrade_log"
#    "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_0/design_1_ECG_Detector_0_0.upgrade_log"
#    "C:/Users/Antti/Documents/GitHub/Vivado/src/coe/diff_8_45.coe"
#    "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_1/design_1_ECG_Detector_0_1.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_bandPass_fir_0_0/design_1_bandPass_fir_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_broadcast_signal_0_0/design_1_broadcast_signal_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_difference_signal_0_0/design_1_difference_signal_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_differentiator_fir_0_0/design_1_differentiator_fir_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_noise_free_signal_0_0/design_1_noise_free_signal_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_raw_signal_0_0/design_1_raw_signal_0_0.upgrade_log"
#    "c:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.upgrade_log"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys"]"

# Create project
create_project ecgSys ./ecgSys

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects ecgSys]
set_property "board_part" "em.avnet.com:zed:part0:0.9" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "C:/Users/Antti/Documents/VivadoProjects/ecgSys/ecgSys.cache/ip" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../../ip_repo"] [file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.cache/ip"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1.bd"]"\
 "[file normalize "$origin_dir/src/coe/real_16_PB_1_40.coe"]"\
 "[file normalize "$origin_dir/src/coe/diff_05_45.coe"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/imports/hdl/design_1_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Unit_0_0/design_1_ECG_Unit_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_0/design_1_ECG_Detector_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../Vivado/src/coe/diff_8_45.coe"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_1/design_1_ECG_Detector_0_1.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_bandPass_fir_0_0/design_1_bandPass_fir_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_broadcast_signal_0_0/design_1_broadcast_signal_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_difference_signal_0_0/design_1_difference_signal_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_differentiator_fir_0_0/design_1_differentiator_fir_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_noise_free_signal_0_0/design_1_noise_free_signal_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_raw_signal_0_0/design_1_raw_signal_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.upgrade_log"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1.bd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/imports/hdl/design_1_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Unit_0_0/design_1_ECG_Unit_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_0/design_1_ECG_Detector_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_ECG_Detector_0_1/design_1_ECG_Detector_0_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_bandPass_fir_0_0/design_1_bandPass_fir_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_broadcast_signal_0_0/design_1_broadcast_signal_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_difference_signal_0_0/design_1_difference_signal_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_differentiator_fir_0_0/design_1_differentiator_fir_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_noise_free_signal_0_0/design_1_noise_free_signal_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_raw_signal_0_0/design_1_raw_signal_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/../../../../../VivadoProjects/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "design_1_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "design_1_wrapper" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:ecgSys"
