# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.cache/wt [current_project]
set_property parent.project_path C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_property ip_repo_paths C:/Users/Antti/Documents/GitHub/Thesis/Vivado/src/ip_repo [current_project]
add_files C:/Users/Antti/Documents/GitHub/Thesis/Vivado/src/ip_repo/ECG_Unit/coe/real_16_PB_1_40.coe
add_files C:/Users/Antti/Documents/GitHub/Thesis/Vivado/src/ip_repo/ECG_Unit/coe/diff_05_45.coe
add_files C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_bandPass_fir_0_0/design_1_bandPass_fir_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_broadcast_signal_0_0/design_1_broadcast_signal_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_difference_signal_0_0/design_1_difference_signal_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_differentiator_fir_0_0/design_1_differentiator_fir_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_noise_free_signal_0_0/design_1_noise_free_signal_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_raw_signal_0_0/design_1_raw_signal_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ecgSys/ecgSys.srcs/sources_1/imports/hdl/design_1_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
