#
# Vivado (TM) v2015.1 (64-bit)
#
# build_new.tcl: Tcl script for re-creating project 'ECG_Detector_v1_0'
#
# Generated by Vivado on Thu May 21 13:53:12 +0300 2015
# IP Build 1209967 on Tue Apr 21 11:39:20 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_new.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/peak_detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/ecg_components.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/multiplier.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/ECG_Detector_v1_0_S_AXI_INTR.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/ECG_Detector_v1_0_CTRL_AXI.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/axis_fifo.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/QRS_Detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/component.xml"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/ECG_Detector_v1_0.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/PQRST_detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/counter.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/TB/tb_ecg_unit.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/QRS_Detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/TB/tb_QRSDet.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/peak_detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/ecg_components.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/QRS_Detector.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/TB/tb_QRSDet.vhd"
#    "C:/Users/Antti/Documents/GitHub/Thesis/Vivado/ip_repo/ECG_Detector_1.0/hdl/peak_detector.vhd"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../../../VivadoProjects/IP_projects/ecg_detector_v1_0_project"]"

# Create project
create_project ECG_Detector_v1_0 ./ECG_Detector_v1_0

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects ECG_Detector_v1_0]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7z020clg484-1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../"] [file normalize "$origin_dir/../"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hdl/peak_detector.vhd"]"\
 "[file normalize "$origin_dir/hdl/ecg_components.vhd"]"\
 "[file normalize "$origin_dir/hdl/multiplier.vhd"]"\
 "[file normalize "$origin_dir/hdl/ECG_Detector_v1_0_S_AXI_INTR.vhd"]"\
 "[file normalize "$origin_dir/hdl/ECG_Detector_v1_0_CTRL_AXI.vhd"]"\
 "[file normalize "$origin_dir/hdl/axis_fifo.vhd"]"\
 "[file normalize "$origin_dir/hdl/QRS_Detector.vhd"]"\
 "[file normalize "$origin_dir/component.xml"]"\
 "[file normalize "$origin_dir/hdl/ECG_Detector_v1_0.vhd"]"\
 "[file normalize "$origin_dir/hdl/PQRST_detector.vhd"]"\
 "[file normalize "$origin_dir/hdl/counter.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "hdl/peak_detector.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/ecg_components.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/multiplier.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/ECG_Detector_v1_0_S_AXI_INTR.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/ECG_Detector_v1_0_CTRL_AXI.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/axis_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/QRS_Detector.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "ECG_Detector_1.0/component.xml"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP-XACT" $file_obj

set file "hdl/ECG_Detector_v1_0.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/PQRST_detector.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/counter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "ECG_Detector_v1_0" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/hdl/TB/tb_ecg_unit.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "TB/tb_ecg_unit.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "tb_ecg_unit" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'QRS_Det' fileset (if not found)
if {[string equal [get_filesets -quiet QRS_Det] ""]} {
  create_fileset -simset QRS_Det
}

# Set 'QRS_Det' fileset object
set obj [get_filesets QRS_Det]
set files [list \
 "[file normalize "$origin_dir/hdl/QRS_Detector.vhd"]"\
 "[file normalize "$origin_dir/hdl/TB/tb_QRSDet.vhd"]"\
 "[file normalize "$origin_dir/hdl/peak_detector.vhd"]"\
 "[file normalize "$origin_dir/hdl/ecg_components.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'QRS_Det' fileset file properties for remote files
# None

# Set 'QRS_Det' fileset file properties for local files
set file "hdl/QRS_Detector.vhd"
set file_obj [get_files -of_objects [get_filesets QRS_Det] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "TB/tb_QRSDet.vhd"
set file_obj [get_files -of_objects [get_filesets QRS_Det] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/peak_detector.vhd"
set file_obj [get_files -of_objects [get_filesets QRS_Det] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/ecg_components.vhd"
set file_obj [get_files -of_objects [get_filesets QRS_Det] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'QRS_Det' fileset properties
set obj [get_filesets QRS_Det]
set_property "top" "tb_QRSDet" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'sim_2' fileset (if not found)
if {[string equal [get_filesets -quiet sim_2] ""]} {
  create_fileset -simset sim_2
}

# Set 'sim_2' fileset object
set obj [get_filesets sim_2]
set files [list \
 "[file normalize "$origin_dir/hdl/QRS_Detector.vhd"]"\
 "[file normalize "$origin_dir/hdl/TB/tb_QRSDet.vhd"]"\
 "[file normalize "$origin_dir/hdl/peak_detector.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_2' fileset file properties for remote files
# None

# Set 'sim_2' fileset file properties for local files
set file "hdl/QRS_Detector.vhd"
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "TB/tb_QRSDet.vhd"
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/peak_detector.vhd"
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_2' fileset properties
set obj [get_filesets sim_2]
set_property "runtime" "" $obj
set_property "source_set" "" $obj
set_property "top" "tb_QRSDet" $obj
set_property "xelab.debug_level" "" $obj
set_property "xelab.load_glbl" "" $obj
set_property "xelab.mt_level" "" $obj
set_property "xelab.nosort" "" $obj
set_property "xelab.rangecheck" "" $obj
set_property "xelab.relax" "" $obj
set_property "xelab.sdf_delay" "" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z020clg484-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z020clg484-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:ECG_Detector_v1_0"
